services:
  server:
    container_name: Server
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - .docker.env
    depends_on:
      - database
      - ollama

  database:
    container_name: Database
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .docker.env

  ollama:
    container_name: Ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  postgres_data:
  ollama_data: